---
#
# Ansible managed
#
repository:
  description: Place custom facts for Ansible on a system.
  homepage: https://buluma.github.io/
  topics: facts, ansible, molecule, tox, playbook, hacktoberfest
