---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: ansible-role-facts
      facts:
        - key: datacenter
          value: Amsterdam
        - key: availability_zone
          value: west
