---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Gather local facts
      ansible.builtin.setup:
        gather_subset:
          - local
    - name: Check if my_fact is set
      ansible.builtin.assert:
        that:
          - ansible_local['custom']['datacenter'] == "Amsterdam"
          - ansible_local['custom']['availability_zone'] == "west"
